#!/usr/bin/env -S bash -e

[ "$#" -lt 3 ] || {
  echo "Usage: $0 <image path> [model]">&2
  exit 1
}

FILENAME="$1"
MODEL="${2-jpn}"

[ "$(tesseract -v 2>/dev/null|head -1|sed 's/^tesseract .*$/e/')" = "e" ] || {
  sudo add-apt-repository ppa:alex-p/tesseract-ocr -y
  sudo apt update -y
  sudo apt install tesseract-ocr libtesseract-dev libgtk2.0-dev -y
}

[ -n "$(tesseract --list-langs|grep Japanese)" ] || {
  sudo apt install tesseract-ocr-jpn  tesseract-ocr-jpn-vert
  sudo apt install tesseract-ocr-script-jpan tesseract-ocr-script-jpan-vert
}

[ -f "$FILENAME" ] || {
  echo "Error: '$FILENAME' is not found">&2
  exit 1
}
echo "#[picture]: $FILENAME"
echo "#[model]:   $MODEL"
echo "#[test: command]"
tesseract "$FILENAME" stdout -l "$MODEL"

echo "#[test: python]"
python -m pip install -U pytesseract Pillow opencv-python -q
python <<A
# https://qiita.com/FukuharaYohei/items/e09049c8d312eaf166a5
import cv2
from PIL import Image
from pprint import pprint
import pytesseract

FILENAME = "$FILENAME"
MODEL = "$MODEL"
im = cv2.imread(FILENAME)
d = pytesseract.image_to_data(im, lang=MODEL,
                              output_type=pytesseract.Output.DICT)
print(d["text"])

for i in range(len(d['level'])):
    x, y = d['left'][i], d['top'][i]
    w, h = d['width'][i], d['height'][i]
    cv2.rectangle(im, (x, y),
                  (x + w, y + h), (0, 255, 0), 2)

try:
    cv2.imshow('img', im)
    while True:
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
except KeyboardInterrupt:
    pass

cv2.destroyAllWindows()
A
